-- DevHub initial application schema.
-- Identity is owned by Clerk; application ownership uses auth.jwt()->>'sub'.

create table public.profiles (
  user_id text primary key default (auth.jwt() ->> 'sub'),
  username text not null unique,
  display_name text not null,
  headline text,
  bio text,
  location text,
  country_code text,
  website_url text,
  github_url text,
  linkedin_url text,
  avatar_path text,
  is_public boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(username, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(display_name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(headline, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(bio, '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(location, '')), 'D')
  ) stored,
  constraint profiles_user_id_length check (char_length(user_id) between 1 and 255),
  constraint profiles_username_format check (
    username = lower(username)
    and username ~ '^[a-z0-9][a-z0-9_]{1,28}[a-z0-9]$'
  ),
  constraint profiles_display_name_length check (
    char_length(btrim(display_name)) between 1 and 80
  ),
  constraint profiles_headline_length check (
    headline is null or char_length(headline) between 1 and 120
  ),
  constraint profiles_bio_length check (bio is null or char_length(bio) <= 1000),
  constraint profiles_location_length check (
    location is null or char_length(location) <= 100
  ),
  constraint profiles_country_code_format check (
    country_code is null or country_code ~ '^[A-Z]{2}$'
  ),
  constraint profiles_website_url_format check (
    website_url is null or (char_length(website_url) <= 500 and website_url ~ '^https?://')
  ),
  constraint profiles_github_url_format check (
    github_url is null or (char_length(github_url) <= 500 and github_url ~ '^https?://')
  ),
  constraint profiles_linkedin_url_format check (
    linkedin_url is null or (char_length(linkedin_url) <= 500 and linkedin_url ~ '^https?://')
  ),
  constraint profiles_avatar_path_length check (
    avatar_path is null or char_length(avatar_path) between 1 and 500
  )
);

create table public.categories (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now(),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint categories_name_length check (char_length(btrim(name)) between 1 and 60),
  constraint categories_sort_order_check check (sort_order >= 0)
);

create table public.technologies (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now(),
  constraint technologies_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint technologies_name_length check (char_length(btrim(name)) between 1 and 60),
  constraint technologies_sort_order_check check (sort_order >= 0)
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id text not null default (auth.jwt() ->> 'sub')
    references public.profiles(user_id) on delete cascade,
  category_id smallint not null references public.categories(id) on delete restrict,
  title text not null,
  summary text not null,
  description text not null,
  demo_url text,
  repository_url text,
  status text not null default 'draft',
  published_at timestamptz,
  like_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(summary, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C')
  ) stored,
  constraint projects_title_length check (char_length(btrim(title)) between 1 and 120),
  constraint projects_summary_length check (char_length(btrim(summary)) between 1 and 240),
  constraint projects_description_length check (
    char_length(btrim(description)) between 1 and 10000
  ),
  constraint projects_demo_url_format check (
    demo_url is null or (char_length(demo_url) <= 500 and demo_url ~ '^https?://')
  ),
  constraint projects_repository_url_format check (
    repository_url is null or (char_length(repository_url) <= 500 and repository_url ~ '^https?://')
  ),
  constraint projects_status_check check (status in ('draft', 'published')),
  constraint projects_like_count_check check (like_count >= 0)
);

create table public.project_images (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  storage_path text not null unique,
  alt_text text not null,
  sort_order smallint not null,
  mime_type text not null,
  byte_size integer not null,
  width integer not null,
  height integer not null,
  created_at timestamptz not null default now(),
  constraint project_images_project_order_unique unique (project_id, sort_order),
  constraint project_images_storage_path_length check (
    char_length(storage_path) between 1 and 500
  ),
  constraint project_images_alt_text_length check (
    char_length(btrim(alt_text)) between 1 and 200
  ),
  constraint project_images_slot_check check (sort_order between 0 and 4),
  constraint project_images_mime_type_check check (
    mime_type in ('image/avif', 'image/jpeg', 'image/png', 'image/webp')
  ),
  constraint project_images_byte_size_check check (byte_size between 1 and 10485760),
  constraint project_images_dimensions_check check (
    width between 1 and 10000 and height between 1 and 10000
  )
);

create table public.project_technologies (
  project_id uuid not null references public.projects(id) on delete cascade,
  technology_id smallint not null references public.technologies(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (project_id, technology_id)
);

create table public.profile_technologies (
  user_id text not null default (auth.jwt() ->> 'sub')
    references public.profiles(user_id) on delete cascade,
  technology_id smallint not null references public.technologies(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (user_id, technology_id)
);

create table public.project_likes (
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id text not null default (auth.jwt() ->> 'sub')
    references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table public.project_saves (
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id text not null default (auth.jwt() ->> 'sub')
    references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table public.clerk_webhook_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clerk_webhook_events_event_id_length check (
    char_length(event_id) between 1 and 255
  ),
  constraint clerk_webhook_events_event_type_length check (
    char_length(event_type) between 1 and 120
  ),
  constraint clerk_webhook_events_status_check check (
    status in ('pending', 'processing', 'completed', 'failed')
  ),
  constraint clerk_webhook_events_attempts_check check (attempts >= 0),
  constraint clerk_webhook_events_last_error_length check (
    last_error is null or char_length(last_error) <= 4000
  )
);

create index profiles_search_document_idx on public.profiles using gin (search_document);
create index projects_search_document_idx on public.projects using gin (search_document);
create index projects_owner_updated_idx on public.projects (owner_id, updated_at desc);
create index projects_public_published_idx
  on public.projects (published_at desc, id)
  where status = 'published';
create index projects_category_published_idx
  on public.projects (category_id, published_at desc, id)
  where status = 'published';
create index project_technologies_technology_project_idx
  on public.project_technologies (technology_id, project_id);
create index profile_technologies_technology_user_idx
  on public.profile_technologies (technology_id, user_id);
create index project_likes_user_created_idx
  on public.project_likes (user_id, created_at desc, project_id);
create index project_saves_user_created_idx
  on public.project_saves (user_id, created_at desc, project_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_project_published_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.status = 'published' then
    if tg_op = 'INSERT' or old.status <> 'published' then
      new.published_at = now();
    end if;
  else
    new.published_at = null;
  end if;

  return new;
end;
$$;

create or replace function public.sync_project_like_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    update public.projects
      set like_count = like_count + 1
      where id = new.project_id;
    return new;
  end if;

  update public.projects
    set like_count = greatest(like_count - 1, 0)
    where id = old.project_id;
  return old;
end;
$$;

revoke all on function public.sync_project_like_count() from public;
revoke all on function public.sync_project_like_count() from anon, authenticated;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

create trigger projects_set_published_at
before insert or update of status on public.projects
for each row execute function public.set_project_published_at();

create trigger clerk_webhook_events_set_updated_at
before update on public.clerk_webhook_events
for each row execute function public.set_updated_at();

create trigger project_likes_sync_count
after insert or delete on public.project_likes
for each row execute function public.sync_project_like_count();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.technologies enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;
alter table public.project_technologies enable row level security;
alter table public.profile_technologies enable row level security;
alter table public.project_likes enable row level security;
alter table public.project_saves enable row level security;
alter table public.clerk_webhook_events enable row level security;

revoke all on table
  public.profiles,
  public.categories,
  public.technologies,
  public.projects,
  public.project_images,
  public.project_technologies,
  public.profile_technologies,
  public.project_likes,
  public.project_saves,
  public.clerk_webhook_events
from anon, authenticated;

grant usage on schema public to anon, authenticated;

grant select on public.categories, public.technologies to anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant insert (
  username, display_name, headline, bio, location, country_code,
  website_url, github_url, linkedin_url, avatar_path, is_public
) on public.profiles to authenticated;
grant update (
  username, display_name, headline, bio, location, country_code,
  website_url, github_url, linkedin_url, avatar_path, is_public
) on public.profiles to authenticated;

grant select on public.projects to anon, authenticated;
grant insert (
  category_id, title, summary, description, demo_url, repository_url, status
) on public.projects to authenticated;
grant update (
  category_id, title, summary, description, demo_url, repository_url, status
) on public.projects to authenticated;
grant delete on public.projects to authenticated;

grant select on public.project_images to anon, authenticated;
grant insert (
  project_id, storage_path, alt_text, sort_order, mime_type, byte_size, width, height
) on public.project_images to authenticated;
grant update (alt_text, sort_order) on public.project_images to authenticated;
grant delete on public.project_images to authenticated;

grant select on public.project_technologies, public.profile_technologies
  to anon, authenticated;
grant insert (project_id, technology_id) on public.project_technologies
  to authenticated;
grant delete on public.project_technologies to authenticated;
grant insert (technology_id) on public.profile_technologies to authenticated;
grant delete on public.profile_technologies to authenticated;

grant select, delete on public.project_likes, public.project_saves to authenticated;
grant insert (project_id) on public.project_likes, public.project_saves to authenticated;

create policy "Public profiles are readable"
on public.profiles for select to anon
using (is_public and deleted_at is null);

create policy "Authenticated users read public or own profile"
on public.profiles for select to authenticated
using (
  (is_public and deleted_at is null)
  or user_id = (select auth.jwt() ->> 'sub')
);

create policy "Users create their own profile"
on public.profiles for insert to authenticated
with check (
  user_id = (select auth.jwt() ->> 'sub')
  and deleted_at is null
);

create policy "Users update their own active profile"
on public.profiles for update to authenticated
using (
  user_id = (select auth.jwt() ->> 'sub')
  and deleted_at is null
)
with check (
  user_id = (select auth.jwt() ->> 'sub')
  and deleted_at is null
);

create policy "Taxonomy is publicly readable"
on public.categories for select to anon, authenticated
using (true);

create policy "Technologies are publicly readable"
on public.technologies for select to anon, authenticated
using (true);

create policy "Published projects from public profiles are readable"
on public.projects for select to anon
using (
  status = 'published'
  and exists (
    select 1 from public.profiles
    where profiles.user_id = projects.owner_id
      and profiles.is_public
      and profiles.deleted_at is null
  )
);

create policy "Authenticated users read public or owned projects"
on public.projects for select to authenticated
using (
  owner_id = (select auth.jwt() ->> 'sub')
  or (
    status = 'published'
    and exists (
      select 1 from public.profiles
      where profiles.user_id = projects.owner_id
        and profiles.is_public
        and profiles.deleted_at is null
    )
  )
);

create policy "Owners create projects"
on public.projects for insert to authenticated
with check (
  owner_id = (select auth.jwt() ->> 'sub')
  and exists (
    select 1 from public.profiles
    where profiles.user_id = (select auth.jwt() ->> 'sub')
      and profiles.deleted_at is null
  )
);

create policy "Owners update projects"
on public.projects for update to authenticated
using (owner_id = (select auth.jwt() ->> 'sub'))
with check (owner_id = (select auth.jwt() ->> 'sub'));

create policy "Owners delete projects"
on public.projects for delete to authenticated
using (owner_id = (select auth.jwt() ->> 'sub'));

create policy "Published project images are readable"
on public.project_images for select to anon
using (
  exists (
    select 1 from public.projects
    where projects.id = project_images.project_id
      and projects.status = 'published'
  )
);

create policy "Authenticated users read public or owned project images"
on public.project_images for select to authenticated
using (
  exists (
    select 1 from public.projects
    where projects.id = project_images.project_id
      and (
        projects.owner_id = (select auth.jwt() ->> 'sub')
        or projects.status = 'published'
      )
  )
);

create policy "Owners create project image metadata"
on public.project_images for insert to authenticated
with check (
  exists (
    select 1 from public.projects
    where projects.id = project_images.project_id
      and projects.owner_id = (select auth.jwt() ->> 'sub')
  )
);

create policy "Owners update project image metadata"
on public.project_images for update to authenticated
using (
  exists (
    select 1 from public.projects
    where projects.id = project_images.project_id
      and projects.owner_id = (select auth.jwt() ->> 'sub')
  )
)
with check (
  exists (
    select 1 from public.projects
    where projects.id = project_images.project_id
      and projects.owner_id = (select auth.jwt() ->> 'sub')
  )
);

create policy "Owners delete project image metadata"
on public.project_images for delete to authenticated
using (
  exists (
    select 1 from public.projects
    where projects.id = project_images.project_id
      and projects.owner_id = (select auth.jwt() ->> 'sub')
  )
);

create policy "Published project technologies are readable"
on public.project_technologies for select to anon
using (
  exists (
    select 1 from public.projects
    where projects.id = project_technologies.project_id
      and projects.status = 'published'
  )
);

create policy "Authenticated users read public or owned project technologies"
on public.project_technologies for select to authenticated
using (
  exists (
    select 1 from public.projects
    where projects.id = project_technologies.project_id
      and (
        projects.owner_id = (select auth.jwt() ->> 'sub')
        or projects.status = 'published'
      )
  )
);

create policy "Owners add project technologies"
on public.project_technologies for insert to authenticated
with check (
  exists (
    select 1 from public.projects
    where projects.id = project_technologies.project_id
      and projects.owner_id = (select auth.jwt() ->> 'sub')
  )
);

create policy "Owners remove project technologies"
on public.project_technologies for delete to authenticated
using (
  exists (
    select 1 from public.projects
    where projects.id = project_technologies.project_id
      and projects.owner_id = (select auth.jwt() ->> 'sub')
  )
);

create policy "Public profile technologies are readable"
on public.profile_technologies for select to anon
using (
  exists (
    select 1 from public.profiles
    where profiles.user_id = profile_technologies.user_id
      and profiles.is_public
      and profiles.deleted_at is null
  )
);

create policy "Authenticated users read public or own profile technologies"
on public.profile_technologies for select to authenticated
using (
  user_id = (select auth.jwt() ->> 'sub')
  or exists (
    select 1 from public.profiles
    where profiles.user_id = profile_technologies.user_id
      and profiles.is_public
      and profiles.deleted_at is null
  )
);

create policy "Users add their profile technologies"
on public.profile_technologies for insert to authenticated
with check (user_id = (select auth.jwt() ->> 'sub'));

create policy "Users remove their profile technologies"
on public.profile_technologies for delete to authenticated
using (user_id = (select auth.jwt() ->> 'sub'));

create policy "Users read their own likes"
on public.project_likes for select to authenticated
using (user_id = (select auth.jwt() ->> 'sub'));

create policy "Users like public projects they do not own"
on public.project_likes for insert to authenticated
with check (
  user_id = (select auth.jwt() ->> 'sub')
  and exists (
    select 1 from public.projects
    where projects.id = project_likes.project_id
      and projects.status = 'published'
      and projects.owner_id <> (select auth.jwt() ->> 'sub')
  )
);

create policy "Users remove their own likes"
on public.project_likes for delete to authenticated
using (user_id = (select auth.jwt() ->> 'sub'));

create policy "Users read their own saves"
on public.project_saves for select to authenticated
using (user_id = (select auth.jwt() ->> 'sub'));

create policy "Users save public projects they do not own"
on public.project_saves for insert to authenticated
with check (
  user_id = (select auth.jwt() ->> 'sub')
  and exists (
    select 1 from public.projects
    where projects.id = project_saves.project_id
      and projects.status = 'published'
      and projects.owner_id <> (select auth.jwt() ->> 'sub')
  )
);

create policy "Users remove their own saves"
on public.project_saves for delete to authenticated
using (user_id = (select auth.jwt() ->> 'sub'));

comment on table public.clerk_webhook_events is
  'Idempotency ledger for a future verified Clerk webhook cleanup path. No client policies or grants.';
